### ISSUE TITLE
The Reverse DNS dataset is not really in CSV format

### ISSUE THREAD

**Issue by zmarty** [rapid7/sonar#10]
Hello folks,

I tried downloading, uncompressing, and parsing as CSV one of these files: https://scans.io/study/sonar.rdns (20170118-rdns.gz)

The documentation says this is CSV: https://github.com/rapid7/sonar/wiki/Reverse-DNS

It's not really CSV because you do not sanitize the column values that have commas.

For example, IP address 107.178.88.73 has reverse DNS www.10mvps.com,.178.107.in-addr.arpa.
(this is the actual value, notice the comma)

I will write some trivial extra code to parse these correctly but I just wanted to point that out, maybe you did not know.

**Comment by jhart-r7** [comment]
@zmarty, thanks for the report -- this is something we are unfortunately aware of.  For Rapid7 folks, we have been tracking this internally as SNR-16.  

For background, we take the domain name directly from the PTR response, so whatever a given nameserver happens to return is what we store.  Unfortunately, as you and others have seen, sometimes some domains on some nameservers return odd results some of the time.   It is unfortunate that these responses are problematic invalid, but it does accurately represent what we saw during the time of the study.  In the case of the IP you gave:

```
$  host  107.178.88.73 
73.88.178.107.in-addr.arpa domain name pointer www.10mvps.com,.178.107.in-addr.arpa.
```

I am not immediately sure what the solution will be here, but I'll air some of the difficulties here, publicly.  We have discussed various encoding/escaping approaches in the past, such as base64, backslashes, etc.  The problem then becomes the fact that scans.io would have two different dataset formats for the same studies over time, requiring folks who blindly pull data from scans.io to handle our new format.

I suspect the approach we'll take here is to have an entirely new study format for RDNS (and probably FDNS too) that'll live in the same location but have a different name syntax so as to make it more obvious that the format changed.    It'll probably be JSON.

Versioning of our datasets is also a possible solution here. 

I'll keep this open since this is public unlike SNR-16.

**Comment by jhart-r7** [comment]
Hello @zmarty and anyone else watching this ticket.

Effective with the future FDNS and RDNS studies, there is a new location and new format.  The new location is https://scans.io/study/sonar.fdns_v2 and https://scans.io/study/sonar.rdns_v2 (which don't exist yet but will once the data is published).  The new format is simple JSON, with `name`, `value`, `type` and `timestamp` fields.

I hope this helps.  Please let us know if you have further questions or concerns with this or any of our data.

Thanks!
